### PR TITLE
fix(window): clamp query window against its current screen

### LINKED ISSUE #1140: Poor multi-monitor support on macOS: window always returns to the main display
### Please confirm the following:

- [x] Be sure to check out [FAQ](https://github.com/tisfeng/Easydict/wiki/FAQ)
- [x] I have carefully read the [README](https://github.com/tisfeng/Easydict#readme)
- [x] I have searched through the [issues](https://github.com/tisfeng/Easydict/issues) page but couldn't find a solution.(Including issue that has been closed)
- [x] Easydict has been upgraded to the [latest version](https://github.com/tisfeng/Easydict/releases)
- [x] I understand and agree to the above, and understand that the project maintainer has limited energy, **issues that do not follow the rules may be ignored or closed directly**

### Problem description

Hi, I’m using the latest Easydict version 2.18.0 on macOS Tahoe.

There seems to be an issue with multi-monitor support.
The app window always goes back to the main display and cannot stay fixed at a specific position on another monitor.

Expected behavior:
The window should remain on the monitor where I place it, and keep its position there.

Actual behavior:
It keeps returning to the main display instead of staying on the secondary display.

Thanks.

### Is the issue consistently reproducible?

Reproducible

### Steps to Reproduce

Hi, I’m using the latest Easydict version 2.18.0 on macOS Tahoe.

There seems to be an issue with multi-monitor support.
The app window always goes back to the main display and cannot stay fixed at a specific position on another monitor.

Expected behavior:
The window should remain on the monitor where I place it, and keep its position there.

Actual behavior:
It keeps returning to the main display instead of staying on the secondary display.

Thanks.

### Screenshot

Image

### Runtime log(zip file)

[MMLogs.zip](https://github.com/user-attachments/files/26560143/MMLogs.zip)

### Expected result

Expected behavior:
The window should remain on the monitor where I place it, and keep its position there.

Actual behavior:
It keeps returning to the main display instead of staying on the secondary display.

### Proposed solution (optional)

None.

### Device type and OS version

Mac studio M4 Max and Macbook Pro M3, macOS Tahoe 26.4

### Are you willing to submit a PR to fix this issue?

- [ ] I'm willing to submit a PR to fix this issue

### PR DESCRIPTION
**Pull request by MoonMao42**
## Summary

Fixes #1140.

On multi-monitor setups, the query window drifts back to the previous
display whenever its content height changes. The user can drag it to a
secondary display, but the next time results stream in or the input
height grows, the window jumps back. On a single monitor the bug is
invisible.

## Root cause

`updateWindowHeightWithLock:` clamps `newFrame` against
`EZLayoutManager.shared.screenVisibleFrame`. That cached value only
refreshes on mouse clicks (plus drags when `fixedWindowPosition` is
`Former`), so it routinely lags the screen the window actually lives on.
`getSafeAreaFrame:` then constrains the new frame to the wrong screen
and `setFrame:` pulls the window back. Every height update reapplies
the clamp, hence the "won't stay put" symptom in #1140.

## Changes

- `EZBaseQueryViewController.updateWindowHeightWithLock:` resolves the
  visible frame from `window.screen` first, falling back to
  `screenForRect:newFrame` and `mainScreen`. `window.screen` uses
  AppKit's largest-overlap rule, which is more reliable than our own
  first-intersect lookup when the window straddles displays.
- `EZCoordinateUtils.h` now declares `screenForRect:`. The
  implementation already existed, only the header was missing.

## Notes

`EZLayoutManager.maximumWindowSize:` still derives its limits from the
cached screen. On displays with very different visible heights the
maximum height can be slightly off, but that is not the cause of the
drift reported here and changing it would touch the layout manager's
public API. Left for a separate PR.

## Test plan

- [ ] Two monitors, drag the fixed window to the secondary display,
      type into the input box: window stays put
- [ ] Same setup with the window pinned, run a query: window does not
      jump back to the primary display while results render
- [x] Single-monitor behaviour unchanged
- [x] Mini and main windows still position correctly under each
      `windowPosition` setting (Mouse / Right / Center / Former)

### CODE REVIEW

**Comment by tisfeng** [comment]
可以，我有一段时间没测多屏幕场景了，很容易忽略这一点。

File: Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m [hunk 1]
```diff
@@ -1685,7 +1685,12 @@ - (void)updateWindowHeightWithLock:(BOOL)lockFlag {
 
     CGRect newFrame = CGRectMake(window.x, y, window.width, showingWindowHeight);
 
-    CGRect screenVisibleFrame = EZLayoutManager.shared.screenVisibleFrame;
+    // Use the window's current screen. The cached one only refreshes on clicks,
+    // so on multi-monitor setups it can yank the window back to the old display.
+    // window.screen picks the display with the largest overlap, which handles
+    // cross-screen drags better than our own first-intersect lookup.
+    NSScreen *currentScreen = window.screen ?: [EZCoordinateUtils screenForRect:newFrame] ?: NSScreen.mainScreen;
```
Comment (tisfeng) [inline Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m:1692]: window.screen 这个属性很棒，我之前居然没发现 😑

Comment (tisfeng) [reply Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m:1692]: 奇怪，我之前添加了这个 [自动翻译](https://github.com/dromara/issues-translate-action) workflow ，为什么前面那条评论会自动翻译 https://github.com/tisfeng/Easydict/pull/1159#issuecomment-4328526863 ，但这个却不会？

Comment (tisfeng) [reply Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m:1692]: 原来是评论类型不一样啊 

image

Comment (MoonMao42) [reply Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m:1692]: 这个bot还挺好用的,终于不用中文转英文还用担心意思是不是自己表达的了,同时外国人来了也能看懂.
#### 之前见过一个fork版本,貌似是直接在编辑原用户的末尾增加翻译,看起来不错,如果有意向可以看看
[翻译bot](https://github.com/lizheming/github-translate-action)
 >好处是直接编辑而不是加一个评论,看起来更高效.坏处是直接编辑可能显得有点侵入性

 而且正好这个版本支持`pull_request_review_comment` 也就是能解决review评论翻译的问题

**Review by tisfeng — APPROVED** [review]
good

File: Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m (hunk 1 above)
Comment (tisfeng) [reply Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m:1692]: 之前没看到这个，，我已经 fork 了一个 https://github.com/tisfeng/issues-translate-action ，实现了 pull_request_review_comment

Comment (tisfeng) [reply Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryViewController.m:1692]: https://github.com/tisfeng/Easydict/pull/1158#discussion_r3156070337

**Comment by yhzhang067** [comment]
感谢修复这个问题！我目前在多显示器场景下也稳定复现这个 bug：查询窗口拖到副屏后，只要结果流式更新或输入框高度变化，窗口就会跳回主屏，对日常使用影响比较明显。

看到 #1159 已经合并到 dev 分支了，请问是否方便尽快发布一个包含该修复的版本，例如 2.18.2 / 2.19.0。

我也可以帮忙测试多屏幕场景下的修复效果。谢谢！
