### PR TITLE
fix: stop button was gone when querying stream service

### LINKED ISSUE #510: dev: OpenAI 翻译的停止按钮不见了
stream 响应时，这里应该有一个暂停按钮的，之前版本有，后面不知道被谁干掉了 😑

image

### PR DESCRIPTION
**Pull request by tisfeng**
Fixed #510 , and 
- enable to stop Gemini stream

https://github.com/tisfeng/Easydict/assets/25194972/5a18a321-3e11-4501-85a2-e259c2d9b75b

### CODE REVIEW

File: Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryWindow.m [hunk 1]
```diff
@@ -128,7 +128,7 @@ - (void)windowDidResignKey:(NSNotification *)notification {
 }
 
 - (void)windowDidResize:(NSNotification *)aNotification {
-    NSLog(@"windowDidResize: %@, windowType: %ld", @(self.frame), self.windowType);
+//    NSLog(@"windowDidResize: %@, windowType: %ld", @(self.frame), self.windowType);
```
Comment (phlpsong) [inline Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryWindow.m:131]: I saw some places where we are using `print` and `NSLog` to print some info,  maybe we could consider using a uniform log method later, we already import packages like `CocoaLumberjack` and `swift-log`.

**Review by phlpsong — APPROVED** [review]

**Review by Jerry23011 — APPROVED** [review]
LGTM

**Review by Jerry23011 — CHANGES_REQUESTED** [review]
截屏2024-04-18 08 17 36
It seems that Stop is not localized under Simplified Chinese

File: Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryWindow.m (hunk 1 above)
Comment (tisfeng) [reply Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryWindow.m:131]: Very good idea!

`swift-log` looks like a library that comes with `CocoaLumberjack`, but I'm not very familiar with `CocoaLumberjack`, and I'm confused about the relationship between them.

We actually have a legacy logging module in our project, `MMLog`, which provides useful crash logs when users experience crashes.

However, I think the `MMLog` code is not very good, it uses a lot of macros, looks complicated, and is not easy to use with external APIs, e.g., it doesn't distinguish well between normal logs, file logs, warning logs, etc. In addition, it uses some deprecated methods, resulting in having to use `#pragma clang diagnostic ignored` to ignore warnings.

I've thought about optimizing this part of the code before, but I'm not familiar with `CocoaLumberjack` and modifying it would be too difficult for me.

If you are familiar with log, can you help optimize this code?

**Comment by tisfeng** [comment]
> 截屏2024-04-18 08 17 36 It seems that Stop is not localized under Simplified Chinese when hovering over the stop streaming button

ok, fixed.

But this `toolTip` is not very useful at the moment, because the way streaming requests are displayed now is so bad that it will cause the UI to keep refreshing and the `toolTip` may not be visible.

In addition, the frequent refresh of streaming request will also lead to UI display bugs and high CPU usage, which I didn't consider when designed the program at the beginning, but it's hard to modify it at the moment, so we can only wait until later to rewrite it with SwiftUI directly 😥

**Comment by Jerry23011** [comment]
looking forward to seeing the rewrite then

**Review by Jerry23011 — APPROVED** [review]

**Review by AkaShark — APPROVED** [review]

**Comment by AkaShark** [comment]
LGTM

File: Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryWindow.m (hunk 1 above)
Comment (phlpsong) [reply Easydict/objc/ViewController/Window/BaseQueryWindow/EZBaseQueryWindow.m:131]: Sure, I checked the documentation, and it seems pretty easy to use. Replacing the existing log should not take long.
